package serialize

import "github.com/Palantir/palantir/model/simulation/setup/material"

var predefinedMaterialsToShieldICRU = map[string]int64{
	"1: Hydrogen":  1,
	"2: Helium":    2,
	"3: Lithium":   3,
	"4: Beryllium": 4,
	"5: Boron":     5,
	"6: Carbon, Amorphous (density2.0 g/cm3)":   6,
	"6: Graphite (density 1.7 g/cm3)":           906,
	"7: Nitrogen":                               7,
	"8: Oxygen":                                 8,
	"9: Fluorine":                               9,
	"10: Neon":                                  10,
	"11: Sodium":                                11,
	"12: Magnesium":                             12,
	"13: Aluminum":                              13,
	"14: Silicon":                               14,
	"15: Phosphorus":                            15,
	"16: Sulfur":                                16,
	"17: Chlorine":                              17,
	"18: Argon":                                 18,
	"19: Potassium":                             19,
	"20: Calcium":                               20,
	"21: Scandium":                              21,
	"22: Titanium":                              22,
	"23: Vanadium":                              23,
	"24: Chromium":                              24,
	"25: Manganese":                             25,
	"26: Iron":                                  26,
	"27: Cobalt":                                27,
	"28: Nickel":                                28,
	"29: Copper":                                29,
	"30: Zinc":                                  30,
	"31: Gallium":                               31,
	"32: Germanium":                             32,
	"33: Arsenic":                               33,
	"34: Selenium":                              34,
	"35: Bromine":                               35,
	"36: Krypton":                               36,
	"37: Rubidium":                              37,
	"38: Strontium":                             38,
	"39: Yttrium":                               39,
	"40: Zirconium":                             40,
	"41: Niobium":                               41,
	"42: Molybdenum":                            42,
	"43: Technetium":                            43,
	"44: Ruthenium":                             44,
	"45: Rhodium":                               45,
	"46: Palladium":                             46,
	"47: Silver":                                47,
	"48: Cadmium":                               48,
	"49: Indium":                                49,
	"50: Tin":                                   50,
	"51: Antimony":                              51,
	"52: Tellurium":                             52,
	"53: Iodine":                                53,
	"54: Xenon":                                 54,
	"55: Cesium":                                55,
	"56: Barium":                                56,
	"57: Lanthanum":                             57,
	"58: Cerium":                                58,
	"59: Praseodymium":                          59,
	"60: Neodymium":                             60,
	"61: Promethium":                            61,
	"62: Samarium":                              62,
	"63: Europium":                              63,
	"64: Gadolinium":                            64,
	"65: Terbium":                               65,
	"66: Dysprosium":                            66,
	"67: Holmium":                               67,
	"68: Erbium":                                68,
	"69: Thulium":                               69,
	"70: Ytterbium":                             70,
	"71: Lutetium":                              71,
	"72: Hafnium":                               72,
	"73: Tantalum":                              73,
	"74: Tungsten":                              74,
	"75: Rhenium":                               75,
	"76: Osmium":                                76,
	"77: Iridium":                               77,
	"78: Platinum":                              78,
	"79: Gold":                                  79,
	"80: Mercury":                               80,
	"81: Thallium":                              81,
	"82: Lead":                                  82,
	"83: Bismuth":                               83,
	"84: Polonium":                              84,
	"85: Astatine":                              85,
	"86: Radon":                                 86,
	"87: Francium":                              87,
	"88: Radium":                                88,
	"89: Actinium":                              89,
	"90: Thorium":                               90,
	"91: Protactinium":                          91,
	"92: Uranium":                               92,
	"93: Neptunium":                             93,
	"94: Plutonium":                             94,
	"95: Americium":                             95,
	"96: Curium":                                96,
	"97: Berkelium":                             97,
	"98: Californium":                           98,
	"A-150 Tissue-Equivalent Plastic":           99,
	"Acetone":                                   100,
	"Acetylene":                                 101,
	"Adenine":                                   102,
	"Adipose Tissue (ICRP)":                     103,
	"Air, Dry (near sea level)":                 104,
	"Alanine":                                   105,
	"Aluminum Oxide":                            106,
	"Amber":                                     107,
	"Ammonia":                                   108,
	"Aniline":                                   109,
	"Anthracene":                                110,
	"B-100 Bone-Equivalent Plastic":             111,
	"Bakelite":                                  112,
	"Barium Fluoride":                           113,
	"Barium Sulfate":                            114,
	"Benzene":                                   115,
	"Beryllium oxide":                           116,
	"Bismuth Germanium oxide":                   117,
	"Blood (ICRP)":                              118,
	"Bone, Compact (ICRU)":                      119,
	"Bone, Cortical (ICRP)":                     120,
	"Boron Carbide":                             121,
	"Boron Oxide":                               122,
	"Brain (ICRP)":                              123,
	"Butane":                                    124,
	"N-Butyl Alcohol":                           125,
	"C-552 Air-Equivalent Plastic":              126,
	"Cadmium Telluride":                         127,
	"Cadmium Tungstate":                         128,
	"Calcium Carbonate":                         129,
	"Calcium Fluoride":                          130,
	"Calcium Oxide":                             131,
	"Calcium Sulfate":                           132,
	"Calcium Tungstate":                         133,
	"Carbon Dioxide":                            134,
	"Carbon Tetrachloride":                      135,
	"Cellulose Acetate, Cellophane":             136,
	"Cellulose Acetate Butyrate":                137,
	"Cellulose Nitrate":                         138,
	"Ceric Sulfate Dosimeter Solution":          139,
	"Cesium Fluoride":                           140,
	"Cesium Iodide":                             141,
	"Chlorobenzene":                             142,
	"Chloroform":                                143,
	"Concrete, Portland":                        144,
	"Cyclohexane":                               145,
	"1,2-Ddihlorobenzene":                       146,
	"Dichlorodiethyl Ether":                     147,
	"1,2-Dichloroethane":                        148,
	"Diethyl Ether":                             149,
	"N,N-Dimethyl Formamide":                    150,
	"Dimethyl Sulfoxide":                        151,
	"Ethane":                                    152,
	"Ethyl Alcohol":                             153,
	"Ethyl Cellulose":                           154,
	"Ethylene":                                  155,
	"Eye Lens (ICRP)":                           156,
	"Ferric Oxide":                              157,
	"Ferroboride":                               158,
	"Ferrous Oxide":                             159,
	"Ferrous Sulfate Dosimeter Solution":        160,
	"Freon-12":                                  161,
	"Freon-12B2":                                162,
	"Freon-13":                                  163,
	"Freon-13B1":                                164,
	"Freon-13I1":                                165,
	"Gadolinium Oxysulfide":                     166,
	"Gallium Arsenide":                          167,
	"Gel in Photographic Emulsion":              168,
	"Glass, Lead":                               169,
	"Glass, Plate":                              170,
	"Glass, Pyrex":                              171,
	"Glucose":                                   172,
	"Glutamine":                                 173,
	"Glycerol":                                  174,
	"Guanine":                                   175,
	"Gypsum, Plaster of Paris":                  176,
	"N-Heptane":                                 177,
	"N-Hexane":                                  178,
	"Kapton Polyimide Film":                     179,
	"Lanthanum Oxybromide":                      180,
	"Lanthanum Oxysulfide":                      181,
	"Lead Oxide":                                182,
	"Lithium Amide":                             183,
	"Lithium Carbonate":                         184,
	"Lithium Fluoride":                          185,
	"Lithium Hydride":                           186,
	"Lithium Iodide":                            187,
	"Lithium Oxide":                             188,
	"Lithium Tetraborate":                       189,
	"Lung (ICRP)":                               190,
	"M3 Wax":                                    191,
	"Magnesium Carbonate":                       192,
	"Magnesium Fluoride":                        193,
	"Magnesium Oxide":                           194,
	"Magnesium Tetraborate":                     195,
	"Mercuric Iodide":                           196,
	"Methane":                                   197,
	"Methanol":                                  198,
	"Mix D Wax":                                 199,
	"MS20 Tissue Substitute":                    200,
	"Muscle, Skeletal":                          201,
	"Muscle, Striated":                          202,
	"Muscle-Equivalent Liquid, with Sucrose":    203,
	"Muscle-Equivalent Liquid, without Sucrose": 204,
	"Naphthalene":                               205,
	"Nitrobenzene":                              206,
	"Nitrous Oxide":                             207,
	"Nylon, Du Pont ELVAmide 8062":              208,
	"Nylon, type 6 and type 6/6":                209,
	"Nylon, type 6/10":                          210,
	"Nylon, type 11 (Rilsan)":                   211,
	"Octane, Liquid":                            212,
	"Paraffin Wax":                              213,
	"N-Pentane":                                 214,
	"Photographic Emulsion":                     215,
	"Plastic Scintillator (Vinyltoluene based)": 216,
	"Plutonium Dioxide":                         217,
	"Polyacrylonitrile":                         218,
	"Polycarbonate (Makrolon, Lexan)":           219,
	"Polychlorostyrene":                         220,
	"Polyethylene":                              221,
	"Polyethylene Terephthalate (Mylar)":        222,
	"Polymethyl Methacralate (Lucite, Perspex)": 223,
	"Polyoxymethylene":                          224,
	"Polypropylene":                             225,
	"Polystyrene":                               226,
	"Polytetrafluoroethylene (Teflon)":          227,
	"Polytrifluorochloroethylene":               228,
	"Polyvinyl Acetate":                         229,
	"Polyvinyl Alcohol":                         230,
	"Polyvinyl Butyral":                         231,
	"Polyvinyl Chloride":                        232,
	"Polyvinylidene Chloride, Saran":            233,
	"Polyvinylidene Fluoride":                   234,
	"Polyvinyl Pyrrolidone":                     235,
	"Potassium Iodide":                          236,
	"Potassium Oxide":                           237,
	"Propane":                                   238,
	"Propane, Liquid":                           239,
	"N-Propyl Alcohol":                          240,
	"Pyridine":                                  241,
	"Rubber, Butyl":                             242,
	"Rubber, Natural":                           243,
	"Rubber, Neoprene":                          244,
	"Silicon Dioxide":                           245,
	"Silver Bromide":                            246,
	"Silver Chloride":                           247,
	"Silver Halides in Photographic Emulsion":   248,
	"Silver Iodide":                             249,
	"Skin (ICRP)":                               250,
	"Sodium Carbonate":                          251,
	"Sodium Iodide":                             252,
	"Sodium Monoxide":                           253,
	"Sodium Nitrate":                            254,
	"Stilbene":                                  255,
	"Sucrose":                                   256,
	"Terphenyl":                                 257,
	"Testes (ICRP)":                             258,
	"Tetrachloroethylene":                       259,
	"Thallium Chloride":                         260,
	"Tissue, Soft (ICRP)":                       261,
	"Tissue, Soft (ICRU four-component)":        262,
	"Tissue-Equivalent GAS (Methane based)":     263,
	"Tissue-Equivalent GAS (Propane based)":     264,
	"Titanium Dioxide":                          265,
	"Toluene":                                   266,
	"Trichloroethylene":                         267,
	"Triethyl Phosphate":                        268,
	"Tungsten Hexafluoride":                     269,
	"Uranium Dicarbide":                         270,
	"Uranium Monocarbide":                       271,
	"Uranium Oxide":                             272,
	"Urea":                                      273,
	"Valine":                                    274,
	"Viton Fluoroelastomer":                     275,
	"Water, Liquid":                             276,
	"Water Vapor":                               277,
	"Xylene":                                    278,
}

var isotopesToShieldNUCLID = map[string]int64{
	"H-1 - Hydrogen":  1,
	"H-2 - Deuterium": 101,
	"H-3 - Tritium":   102,
	"He-3":            104,
	"He-4":            2,
	"Li-6":            105,
	"Li-7":            3,
	"Be-9":            4,
	"B-10":            106,
	"B-11":            5,
	"C-*":             6,
	"N-*":             7,
	"O-*":             8,
	"F-19":            9,
	"Na-23":           11,
	"Mg-*":            12,
	"Al-27":           13,
	"Si-*":            14,
	"P-31":            15,
	"S-*":             16,
	"Cl-*":            17,
	"Ar-*":            18,
	"K-*":             19,
	"Ca-*":            20,
	"Ti-*":            22,
	"V-51":            23,
	"Cr-*":            24,
	"Mn-55":           25,
	"Fe-*":            26,
	"Co-59":           27,
	"Ni-*":            28,
	"Cu-*":            29,
	"Zn-*":            30,
	"Ga-*":            31,
	"Ge-*":            32,
	"As-75":           33,
	"Nb-93":           41,
	"Mo-*":            42,
	"Ag-*":            47,
	"Cd-*":            48,
	"Sn-*":            50,
	"Eu-*":            63,
	"Gd-*":            64,
	"Er-*":            68,
	"Ta-181":          73,
	"W-*":             74,
	"Re-*":            75,
	"Au-187":          79,
	"Hg-*":            80,
	"Pb-*":            82,
	"Bi-209":          83,
	"Th-232":          90,
	"U-235":           103,
	"U-238":           92,
	"Pu-239":          94,
	"Pu-240":          107,
}

var stateOfMatterToShield = map[material.StateOfMatter]int64{
	material.Solid:  0,
	material.Gas:    1,
	material.Liquid: 2,
}
