FROM node:18

# Create app directory
WORKDIR /usr/src/app

# fix permissions for openshift container, such that any user can read/write
RUN chgrp -R 0 /usr/src/app
RUN chmod -R g=u /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
COPY . .

# install python3-pip via apt and clean cache
RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*

RUN npm run setup

EXPOSE 3000

# run the app via npm run start-demo
CMD [ "npm", "run", "start-demo" ]
