version: '3.3'

services:
    yaptide_ui:
        build:
            context: .
            dockerfile: Dockerfile
        image: yaptide_ui
        container_name: yaptide_ui
        ports:
            - 80:80
            - 443:443

    keycloak:
        image: quay.io/keycloak/keycloak:23.0.1
        container_name: keycloak
        ports:
            - 8080:8080
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        # Import realms from JSON: https://www.keycloak.org/server/containers#_importing_a_realm_on_startup
        # Setting auth prefix for backward compatibility: https://www.keycloak.org/server/all-config
        command: ["start-dev",  "--http-relative-path", "/auth", "--import-realm"]
        volumes:
            - ./keycloak_config:/opt/keycloak/data/import:ro
