site_name: Documentation
site_url: https://yaptide.github.io/ui/
repo_url: https://github.com/yaptide/ui
repo_name: yaptide/ui
copyright: Copyright &copy; 2023 the Yaptide team


theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
- Home:
  - Overview: index.md

plugins:
- search
