export const COMMON_MATERIAL_ICRUS = [104, 276, 223, 179, 222, 6, 13, 14, 82, 245, 170, 1000];
export const DEFAULT_MATERIAL_ICRU = 1;
export const DEFAULT_MATERIAL_NAME = 'Hydrogen';
export const DEFAULT_SANITIZED_MATERIAL_NAME = 'G4_H';
export const DEFAULT_MATERIAL_DENSITY = 8.3748e-5;

export const MATERIALS_GEANT = [
	{ icru: 1, name: 'Hydrogen', sanitized_name: 'G4_H', density: 8.3748e-5 },
	{ icru: 2, name: 'Helium', sanitized_name: 'G4_He', density: 0.000166322 },
	{ icru: 3, name: 'Lithium', sanitized_name: 'G4_Li', density: 0.534 },
	{ icru: 4, name: 'Beryllium', sanitized_name: 'G4_Be', density: 1.848 },
	{ icru: 5, name: 'Boron', sanitized_name: 'G4_B', density: 2.37 },
	{ icru: 6, name: 'Carbon', sanitized_name: 'G4_C', density: 2 },
	{ icru: 7, name: 'Nitrogen', sanitized_name: 'G4_N', density: 0.0011652 },
	{ icru: 8, name: 'Oxygen', sanitized_name: 'G4_O', density: 0.00133151 },
	{ icru: 9, name: 'Fluorine', sanitized_name: 'G4_F', density: 0.00158029 },
	{ icru: 10, name: 'Neon', sanitized_name: 'G4_Ne', density: 0.000838505 },
	{ icru: 11, name: 'Sodium', sanitized_name: 'G4_Na', density: 0.971 },
	{ icru: 12, name: 'Magnesium', sanitized_name: 'G4_Mg', density: 1.74 },
	{ icru: 13, name: 'Aluminum', sanitized_name: 'G4_Al', density: 2.699 },
	{ icru: 14, name: 'Silicon', sanitized_name: 'G4_Si', density: 2.33 },
	{ icru: 15, name: 'Phosphorus', sanitized_name: 'G4_P', density: 2.2 },
	{ icru: 16, name: 'Sulfur', sanitized_name: 'G4_S', density: 2 },
	{ icru: 17, name: 'Chlorine', sanitized_name: 'G4_Cl', density: 0.00299473 },
	{ icru: 18, name: 'Argon', sanitized_name: 'G4_Ar', density: 0.00166201 },
	{ icru: 19, name: 'Potassium', sanitized_name: 'G4_K', density: 0.862 },
	{ icru: 20, name: 'Calcium', sanitized_name: 'G4_Ca', density: 1.55 },
	{ icru: 21, name: 'Scandium', sanitized_name: 'G4_Sc', density: 2.989 },
	{ icru: 22, name: 'Titanium', sanitized_name: 'G4_Ti', density: 4.54 },
	{ icru: 23, name: 'Vanadium', sanitized_name: 'G4_V', density: 6.11 },
	{ icru: 24, name: 'Chromium', sanitized_name: 'G4_Cr', density: 7.18 },
	{ icru: 25, name: 'Manganese', sanitized_name: 'G4_Mn', density: 7.44 },
	{ icru: 26, name: 'Iron', sanitized_name: 'G4_Fe', density: 7.874 },
	{ icru: 27, name: 'Cobalt', sanitized_name: 'G4_Co', density: 8.9 },
	{ icru: 28, name: 'Nickel', sanitized_name: 'G4_Ni', density: 8.902 },
	{ icru: 29, name: 'Copper', sanitized_name: 'G4_Cu', density: 8.96 },
	{ icru: 30, name: 'Zinc', sanitized_name: 'G4_Zn', density: 7.133 },
	{ icru: 31, name: 'Gallium', sanitized_name: 'G4_Ga', density: 5.904 },
	{ icru: 32, name: 'Germanium', sanitized_name: 'G4_Ge', density: 5.323 },
	{ icru: 33, name: 'Arsenic', sanitized_name: 'G4_As', density: 5.73 },
	{ icru: 34, name: 'Selenium', sanitized_name: 'G4_Se', density: 4.5 },
	{ icru: 35, name: 'Bromine', sanitized_name: 'G4_Br', density: 0.0070721 },
	{ icru: 36, name: 'Krypton', sanitized_name: 'G4_Kr', density: 0.00347832 },
	{ icru: 37, name: 'Rubidium', sanitized_name: 'G4_Rb', density: 1.532 },
	{ icru: 38, name: 'Strontium', sanitized_name: 'G4_Sr', density: 2.54 },
	{ icru: 39, name: 'Yttrium', sanitized_name: 'G4_Y', density: 4.469 },
	{ icru: 40, name: 'Zirconium', sanitized_name: 'G4_Zr', density: 6.506 },
	{ icru: 41, name: 'Niobium', sanitized_name: 'G4_Nb', density: 8.57 },
	{ icru: 42, name: 'Molybdenum', sanitized_name: 'G4_Mo', density: 10.22 },
	{ icru: 43, name: 'Technetium', sanitized_name: 'G4_Tc', density: 11.5 },
	{ icru: 44, name: 'Ruthenium', sanitized_name: 'G4_Ru', density: 12.41 },
	{ icru: 45, name: 'Rhodium', sanitized_name: 'G4_Rh', density: 12.41 },
	{ icru: 46, name: 'Palladium', sanitized_name: 'G4_Pd', density: 12.02 },
	{ icru: 47, name: 'Silver', sanitized_name: 'G4_Ag', density: 10.5 },
	{ icru: 48, name: 'Cadmium', sanitized_name: 'G4_Cd', density: 8.65 },
	{ icru: 49, name: 'Indium', sanitized_name: 'G4_In', density: 7.31 },
	{ icru: 50, name: 'Tin', sanitized_name: 'G4_Sn', density: 7.31 },
	{ icru: 51, name: 'Antimony', sanitized_name: 'G4_Sb', density: 6.691 },
	{ icru: 52, name: 'Tellurium', sanitized_name: 'G4_Te', density: 6.24 },
	{ icru: 53, name: 'Iodine', sanitized_name: 'G4_I', density: 4.93 },
	{ icru: 54, name: 'Xenon', sanitized_name: 'G4_Xe', density: 0.00548536 },
	{ icru: 55, name: 'Cesium', sanitized_name: 'G4_Cs', density: 1.873 },
	{ icru: 56, name: 'Barium', sanitized_name: 'G4_Ba', density: 3.5 },
	{ icru: 57, name: 'Lanthanum', sanitized_name: 'G4_La', density: 6.154 },
	{ icru: 58, name: 'Cerium', sanitized_name: 'G4_Ce', density: 6.657 },
	{ icru: 59, name: 'Praseodymium', sanitized_name: 'G4_Pr', density: 6.71 },
	{ icru: 60, name: 'Neodymium', sanitized_name: 'G4_Nd', density: 6.9 },
	{ icru: 61, name: 'Promethium', sanitized_name: 'G4_Pm', density: 7.22 },
	{ icru: 62, name: 'Samarium', sanitized_name: 'G4_Sm', density: 7.46 },
	{ icru: 63, name: 'Europium', sanitized_name: 'G4_Eu', density: 5.243 },
	{ icru: 64, name: 'Gadolinium', sanitized_name: 'G4_Gd', density: 7.9004 },
	{ icru: 65, name: 'Terbium', sanitized_name: 'G4_Tb', density: 8.229 },
	{ icru: 66, name: 'Dysprosium', sanitized_name: 'G4_Dy', density: 8.55 },
	{ icru: 67, name: 'Holmium', sanitized_name: 'G4_Ho', density: 8.795 },
	{ icru: 68, name: 'Erbium', sanitized_name: 'G4_Er', density: 9.066 },
	{ icru: 69, name: 'Thulium', sanitized_name: 'G4_Tm', density: 9.321 },
	{ icru: 70, name: 'Ytterbium', sanitized_name: 'G4_Yb', density: 6.73 },
	{ icru: 71, name: 'Lutetium', sanitized_name: 'G4_Lu', density: 9.84 },
	{ icru: 72, name: 'Hafnium', sanitized_name: 'G4_Hf', density: 13.31 },
	{ icru: 73, name: 'Tantalum', sanitized_name: 'G4_Ta', density: 16.654 },
	{ icru: 74, name: 'Tungsten', sanitized_name: 'G4_W', density: 19.3 },
	{ icru: 75, name: 'Rhenium', sanitized_name: 'G4_Re', density: 21.02 },
	{ icru: 76, name: 'Osmium', sanitized_name: 'G4_Os', density: 22.57 },
	{ icru: 77, name: 'Iridium', sanitized_name: 'G4_Ir', density: 22.42 },
	{ icru: 78, name: 'Platinum', sanitized_name: 'G4_Pt', density: 21.45 },
	{ icru: 79, name: 'Gold', sanitized_name: 'G4_Au', density: 19.32 },
	{ icru: 80, name: 'Mercury', sanitized_name: 'G4_Hg', density: 13.546 },
	{ icru: 81, name: 'Thallium', sanitized_name: 'G4_Tl', density: 11.72 },
	{ icru: 82, name: 'Lead', sanitized_name: 'G4_Pb', density: 11.35 },
	{ icru: 83, name: 'Bismuth', sanitized_name: 'G4_Bi', density: 9.747 },
	{ icru: 84, name: 'Polonium', sanitized_name: 'G4_Po', density: 9.32 },
	{ icru: 85, name: 'Astatine', sanitized_name: 'G4_At', density: 9.32 },
	{ icru: 86, name: 'Radon', sanitized_name: 'G4_Rn', density: 0.00900662 },
	{ icru: 87, name: 'Francium', sanitized_name: 'G4_Fr', density: 1 },
	{ icru: 88, name: 'Radium', sanitized_name: 'G4_Ra', density: 5 },
	{ icru: 89, name: 'Actinium', sanitized_name: 'G4_Ac', density: 10.07 },
	{ icru: 90, name: 'Thorium', sanitized_name: 'G4_Th', density: 11.72 },
	{ icru: 91, name: 'Protactinium', sanitized_name: 'G4_Pa', density: 15.37 },
	{ icru: 92, name: 'Uranium', sanitized_name: 'G4_U', density: 18.95 },
	{ icru: 93, name: 'Neptunium', sanitized_name: 'G4_Np', density: 20.25 },
	{ icru: 94, name: 'Plutonium', sanitized_name: 'G4_Pu', density: 19.84 },
	{ icru: 95, name: 'Americium', sanitized_name: 'G4_Am', density: 13.67 },
	{ icru: 96, name: 'Curium', sanitized_name: 'G4_Cm', density: 13.51 },
	{ icru: 97, name: 'Berkelium', sanitized_name: 'G4_Bk', density: 14 },
	{ icru: 98, name: 'Californium', sanitized_name: 'G4_Cf', density: 10 }
];

export const DEFAULT_SIMULATION_MATERIAL = MATERIALS_GEANT.find(
	mat => mat.icru === DEFAULT_MATERIAL_ICRU
)!;
