package material

var predefinedMaterials = []string{
	"1: Hydrogen",
	"2: Helium",
	"3: Lithium",
	"4: Beryllium",
	"5: Boron",
	"6: Carbon, Amorphous (density2.0 g/cm3)",
	"6: Graphite (density 1.7 g/cm3)",
	"7: Nitrogen",
	"8: Oxygen",
	"9: Fluorine",
	"10: Neon",
	"11: Sodium",
	"12: Magnesium",
	"13: Aluminum",
	"14: Silicon",
	"15: Phosphorus",
	"16: Sulfur",
	"17: Chlorine",
	"18: Argon",
	"19: Potassium",
	"20: Calcium",
	"21: Scandium",
	"22: Titanium",
	"23: Vanadium",
	"24: Chromium",
	"25: Manganese",
	"26: Iron",
	"27: Cobalt",
	"28: Nickel",
	"29: Copper",
	"30: Zinc",
	"31: Gallium",
	"32: Germanium",
	"33: Arsenic",
	"34: Selenium",
	"35: Bromine",
	"36: Krypton",
	"37: Rubidium",
	"38: Strontium",
	"39: Yttrium",
	"40: Zirconium",
	"41: Niobium",
	"42: Molybdenum",
	"43: Technetium",
	"44: Ruthenium",
	"45: Rhodium",
	"46: Palladium",
	"47: Silver",
	"48: Cadmium",
	"49: Indium",
	"50: Tin",
	"51: Antimony",
	"52: Tellurium",
	"53: Iodine",
	"54: Xenon",
	"55: Cesium",
	"56: Barium",
	"57: Lanthanum",
	"58: Cerium",
	"59: Praseodymium",
	"60: Neodymium",
	"61: Promethium",
	"62: Samarium",
	"63: Europium",
	"64: Gadolinium",
	"65: Terbium",
	"66: Dysprosium",
	"67: Holmium",
	"68: Erbium",
	"69: Thulium",
	"70: Ytterbium",
	"71: Lutetium",
	"72: Hafnium",
	"73: Tantalum",
	"74: Tungsten",
	"75: Rhenium",
	"76: Osmium",
	"77: Iridium",
	"78: Platinum",
	"79: Gold",
	"80: Mercury",
	"81: Thallium",
	"82: Lead",
	"83: Bismuth",
	"84: Polonium",
	"85: Astatine",
	"86: Radon",
	"87: Francium",
	"88: Radium",
	"89: Actinium",
	"90: Thorium",
	"91: Protactinium",
	"92: Uranium",
	"93: Neptunium",
	"94: Plutonium",
	"95: Americium",
	"96: Curium",
	"97: Berkelium",
	"98: Californium",
	"A-150 Tissue-Equivalent Plastic",
	"Acetone",
	"Acetylene",
	"Adenine",
	"Adipose Tissue (ICRP)",
	"Air, Dry (near sea level)",
	"Alanine",
	"Aluminum Oxide",
	"Amber",
	"Ammonia",
	"Aniline",
	"Anthracene",
	"B-100 Bone-Equivalent Plastic",
	"Bakelite",
	"Barium Fluoride",
	"Barium Sulfate",
	"Benzene",
	"Beryllium oxide",
	"Bismuth Germanium oxide",
	"Blood (ICRP)",
	"Bone, Compact (ICRU)",
	"Bone, Cortical (ICRP)",
	"Boron Carbide",
	"Boron Oxide",
	"Brain (ICRP)",
	"Butane",
	"N-Butyl Alcohol",
	"C-552 Air-Equivalent Plastic",
	"Cadmium Telluride",
	"Cadmium Tungstate",
	"Calcium Carbonate",
	"Calcium Fluoride",
	"Calcium Oxide",
	"Calcium Sulfate",
	"Calcium Tungstate",
	"Carbon Dioxide",
	"Carbon Tetrachloride",
	"Cellulose Acetate, Cellophane",
	"Cellulose Acetate Butyrate",
	"Cellulose Nitrate",
	"Ceric Sulfate Dosimeter Solution",
	"Cesium Fluoride",
	"Cesium Iodide",
	"Chlorobenzene",
	"Chloroform",
	"Concrete, Portland",
	"Cyclohexane",
	"1,2-Ddihlorobenzene",
	"Dichlorodiethyl Ether",
	"1,2-Dichloroethane",
	"Diethyl Ether",
	"N,N-Dimethyl Formamide",
	"Dimethyl Sulfoxide",
	"Ethane",
	"Ethyl Alcohol",
	"Ethyl Cellulose",
	"Ethylene",
	"Eye Lens (ICRP)",
	"Ferric Oxide",
	"Ferroboride",
	"Ferrous Oxide",
	"Ferrous Sulfate Dosimeter Solution",
	"Freon-12",
	"Freon-12B2",
	"Freon-13",
	"Freon-13B1",
	"Freon-13I1",
	"Gadolinium Oxysulfide",
	"Gallium Arsenide",
	"Gel in Photographic Emulsion",
	"Glass, Lead",
	"Glass, Plate",
	"Glass, Pyrex",
	"Glucose",
	"Glutamine",
	"Glycerol",
	"Guanine",
	"Gypsum, Plaster of Paris",
	"N-Heptane",
	"N-Hexane",
	"Kapton Polyimide Film",
	"Lanthanum Oxybromide",
	"Lanthanum Oxysulfide",
	"Lead Oxide",
	"Lithium Amide",
	"Lithium Carbonate",
	"Lithium Fluoride",
	"Lithium Hydride",
	"Lithium Iodide",
	"Lithium Oxide",
	"Lithium Tetraborate",
	"Lung (ICRP)",
	"M3 Wax",
	"Magnesium Carbonate",
	"Magnesium Fluoride",
	"Magnesium Oxide",
	"Magnesium Tetraborate",
	"Mercuric Iodide",
	"Methane",
	"Methanol",
	"Mix D Wax",
	"MS20 Tissue Substitute",
	"Muscle, Skeletal",
	"Muscle, Striated",
	"Muscle-Equivalent Liquid, with Sucrose",
	"Muscle-Equivalent Liquid, without Sucrose",
	"Naphthalene",
	"Nitrobenzene",
	"Nitrous Oxide",
	"Nylon, Du Pont ELVAmide 8062",
	"Nylon, type 6 and type 6/6",
	"Nylon, type 6/10",
	"Nylon, type 11 (Rilsan)",
	"Octane, Liquid",
	"Paraffin Wax",
	"N-Pentane",
	"Photographic Emulsion",
	"Plastic Scintillator (Vinyltoluene based)",
	"Plutonium Dioxide",
	"Polyacrylonitrile",
	"Polycarbonate (Makrolon, Lexan)",
	"Polychlorostyrene",
	"Polyethylene",
	"Polyethylene Terephthalate (Mylar)",
	"Polymethyl Methacralate (Lucite, Perspex)",
	"Polyoxymethylene",
	"Polypropylene",
	"Polystyrene",
	"Polytetrafluoroethylene (Teflon)",
	"Polytrifluorochloroethylene",
	"Polyvinyl Acetate",
	"Polyvinyl Alcohol",
	"Polyvinyl Butyral",
	"Polyvinyl Chloride",
	"Polyvinylidene Chloride, Saran",
	"Polyvinylidene Fluoride",
	"Polyvinyl Pyrrolidone",
	"Potassium Iodide",
	"Potassium Oxide",
	"Propane",
	"Propane, Liquid",
	"N-Propyl Alcohol",
	"Pyridine",
	"Rubber, Butyl",
	"Rubber, Natural",
	"Rubber, Neoprene",
	"Silicon Dioxide",
	"Silver Bromide",
	"Silver Chloride",
	"Silver Halides in Photographic Emulsion",
	"Silver Iodide",
	"Skin (ICRP)",
	"Sodium Carbonate",
	"Sodium Iodide",
	"Sodium Monoxide",
	"Sodium Nitrate",
	"Stilbene",
	"Sucrose",
	"Terphenyl",
	"Testes (ICRP)",
	"Tetrachloroethylene",
	"Thallium Chloride",
	"Tissue, Soft (ICRP)",
	"Tissue, Soft (ICRU four-component)",
	"Tissue-Equivalent GAS (Methane based)",
	"Tissue-Equivalent GAS (Propane based)",
	"Titanium Dioxide",
	"Toluene",
	"Trichloroethylene",
	"Triethyl Phosphate",
	"Tungsten Hexafluoride",
	"Uranium Dicarbide",
	"Uranium Monocarbide",
	"Uranium Oxide",
	"Urea",
	"Valine",
	"Viton Fluoroelastomer",
	"Water, Liquid",
	"Water Vapor",
	"Xylene",
}

var isotopes = []string{
	"H-1 - Hydrogen",
	"H-2 - Deuterium",
	"H-3 - Tritium",
	"He-3",
	"He-4",
	"Li-6",
	"Li-7",
	"Be-9",
	"B-10",
	"B-11",
	"C-*",
	"N-*",
	"O-*",
	"F-19",
	"Na-23",
	"Mg-*",
	"Al-27",
	"Si-*",
	"P-31",
	"S-*",
	"Cl-*",
	"Ar-*",
	"K-*",
	"Ca-*",
	"Ti-*",
	"V-51",
	"Cr-*",
	"Mn-55",
	"Fe-*",
	"Co-59",
	"Ni-*",
	"Cu-*",
	"Zn-*",
	"Ga-*",
	"Ge-*",
	"As-75",
	"Nb-93",
	"Mo-*",
	"Ag-*",
	"Cd-*",
	"Sn-*",
	"Eu-*",
	"Gd-*",
	"Er-*",
	"Ta-181",
	"W-*",
	"Re-*",
	"Au-187",
	"Hg-*",
	"Pb-*",
	"Bi-209",
	"Th-232",
	"U-235",
	"U-238",
	"Pu-239",
	"Pu-240",
}

// PredefinedMaterials return list of all available names for material.Predefined.
func PredefinedMaterials() []string {
	return predefinedMaterials
}

// Isotopes return list of all available isotopes names for material.Element.
func Isotopes() []string {
	return isotopes
}
