export const COMMON_MATERIAL_ICRUS = [104, 276, 223, 179, 222, 6, 245, 170, 1000];
export const DEFAULT_MATERIAL_ICRU = 276;
export const DEFAULT_MATERIAL_NAME = 'WATER, LIQUID';
// made with:
//
// import json
// result = []
// with open('07_reftab.tex', 'r') as infile:
//     for line in infile.readlines():
//         data = line.strip().split()
//         materialId = data[0]
//         materialName = ' '.join(data[2:])[1:-2]
//         result.append({'icru': materialId, 'name': materialName})
//         print(materialId, materialName)
// with open('materials.txt', 'w') as outfile:
//     json.dump(result, outfile)

export const MATERIALS = [
	{ icru: 1000, name: 'VACUUM' },
	{ icru: 0, name: 'BLACK HOLE' },
	{ icru: 1, name: 'HYDROGEN' },
	{ icru: 2, name: 'HELIUM' },
	{ icru: 3, name: 'LITHIUM' },
	{ icru: 4, name: 'BERYLLIUM' },
	{ icru: 5, name: 'BORON' },
	{ icru: 6, name: 'AMORPHOUS CARBON (density 2.0 g/cm3)' },
	{ icru: 906, name: 'GRAPHITE' },
	{ icru: 7, name: 'NITROGEN' },
	{ icru: 8, name: 'OXYGEN' },
	{ icru: 98, name: 'CALIFORNIUM' },
	{ icru: 99, name: 'A-150 TISSUE-EQUIVALENT PLASTIC' },
	{ icru: 100, name: 'ACETONE' },
	{ icru: 101, name: 'ACETYLENE' },
	{ icru: 102, name: 'ADENINE' },
	{ icru: 103, name: 'ADIPOSE TISSUE (ICRP)' },
	{ icru: 104, name: 'AIR, DRY (NEAR SEA LEVEL)' },
	{ icru: 105, name: 'ALANINE' },
	{ icru: 106, name: 'ALUMINUM OXIDE' },
	{ icru: 107, name: 'AMBER' },
	{ icru: 108, name: 'AMMONIA' },
	{ icru: 109, name: 'ANILINE' },
	{ icru: 110, name: 'ANTHRACENE' },
	{ icru: 111, name: 'B100' },
	{ icru: 112, name: 'BAKELITE' },
	{ icru: 113, name: 'BARIUM FLUORIDE' },
	{ icru: 114, name: 'BARIUM SULFATE' },
	{ icru: 115, name: 'BENZENE' },
	{ icru: 116, name: 'BERYLLIUM OXIDE' },
	{ icru: 117, name: 'BISMUTH GERMANIUM OXIDE' },
	{ icru: 118, name: 'BLOOD (ICRP)' },
	{ icru: 119, name: 'BONE, COMPACT (ICRU)' },
	{ icru: 120, name: 'BONE, CORTICAL (ICRP)' },
	{ icru: 121, name: 'BORON CARBIDE' },
	{ icru: 122, name: 'BORON OXIDE' },
	{ icru: 123, name: 'BRAIN (ICRP)' },
	{ icru: 124, name: 'BUTANE' },
	{ icru: 125, name: 'N-BUTYLALCOHOL' },
	{ icru: 126, name: 'C-552 AIR-EQUIVALENT PLASTIC' },
	{ icru: 127, name: 'CADMIUM TELLURIDE' },
	{ icru: 128, name: 'CADMIUM TUNGSTATE' },
	{ icru: 129, name: 'CALCIUM CARBONATE' },
	{ icru: 130, name: 'CALCIUM FLUORIDE' },
	{ icru: 131, name: 'CALCIUM OXIDE' },
	{ icru: 132, name: 'CALCIUM SULFATE' },
	{ icru: 133, name: 'CALCIUM TUNGSTATE' },
	{ icru: 134, name: 'CARBON DIOXIDE' },
	{ icru: 135, name: 'CARBON TETRACHLORIDE' },
	{ icru: 136, name: 'CELLULOSE ACETATE, CELLOPHANE' },
	{ icru: 137, name: 'CELLULOSE ACETATE BUTYRATE' },
	{ icru: 138, name: 'CELLULOSE NITRATE' },
	{ icru: 139, name: 'CERIC SULFATE DOSIMETER SOLUTION' },
	{ icru: 140, name: 'CESIUM FLUORIDE' },
	{ icru: 141, name: 'CESIUM IODIDE' },
	{ icru: 142, name: 'CHLOROBENZENE' },
	{ icru: 143, name: 'CHLOROFORM' },
	{ icru: 144, name: 'CONCRETE PORTLAND' },
	{ icru: 145, name: 'CYCLOHEXANE' },
	{ icru: 146, name: '1,2-DICHLOROBENZENE' },
	{ icru: 147, name: 'DICHLORODIETHYL ETHER' },
	{ icru: 148, name: 'DICHLOROETHANE' },
	{ icru: 149, name: 'DIETHYLETHER' },
	{ icru: 150, name: 'N,N-DIMETHYL FORMAMIDE' },
	{ icru: 151, name: 'DIMETHYLSULFOXIDE' },
	{ icru: 152, name: 'ETHANE' },
	{ icru: 153, name: 'ETHYL ALCOHOL' },
	{ icru: 154, name: 'ETHYL CELLULOSE' },
	{ icru: 155, name: 'ETHYLENE' },
	{ icru: 156, name: 'EYELENS (ICRP)' },
	{ icru: 157, name: 'FERRIC OXIDE' },
	{ icru: 158, name: 'FERRO BORIDE' },
	{ icru: 159, name: 'FERROUS OXIDE' },
	{ icru: 160, name: 'FERROUS SULFATE DOSIMETER SOLUTION' },
	{ icru: 161, name: 'FREON-12' },
	{ icru: 162, name: 'FREON-12B2' },
	{ icru: 163, name: 'FREON-13' },
	{ icru: 164, name: 'FREON-13B1' },
	{ icru: 165, name: 'FREON-13I1' },
	{ icru: 166, name: 'GADOLINIUM OXYSULFIDE' },
	{ icru: 167, name: 'GALLIUM ARSENIDE' },
	{ icru: 168, name: 'GEL IN PHOTOGRAPHIC EMULSION' },
	{ icru: 169, name: 'GLASS, PYREX' },
	{ icru: 170, name: 'GLASS, LEAD' },
	{ icru: 171, name: 'GLASS, PLATE' },
	{ icru: 172, name: 'GLUCOSE' },
	{ icru: 173, name: 'GLUTAMINE' },
	{ icru: 174, name: 'GLYCEROL' },
	{ icru: 175, name: 'GUANINE' },
	{ icru: 176, name: 'GYPSUM / PLASTER OF PARIS' },
	{ icru: 177, name: 'N-HEPTANE' },
	{ icru: 178, name: 'N-HEXANE' },
	{ icru: 179, name: 'KAPTON POLYIMIDE FILM' },
	{ icru: 180, name: 'LANTHANUM OXYBROMIDE' },
	{ icru: 181, name: 'LANTHANUM OXYSULFIDE' },
	{ icru: 182, name: 'LEADOXIDE' },
	{ icru: 183, name: 'LITHIUM AMIDE' },
	{ icru: 184, name: 'LITHIUM CARBONATE' },
	{ icru: 185, name: 'LITHIUM FLUORIDE' },
	{ icru: 186, name: 'LITHIUM HYDRIDE' },
	{ icru: 187, name: 'LITHIUM IODIDE' },
	{ icru: 188, name: 'LITHIUM OXIDE' },
	{ icru: 189, name: 'LITHIUM TETRABORATE' },
	{ icru: 190, name: 'LUNG (ICRP)' },
	{ icru: 191, name: 'M3 WAX' },
	{ icru: 192, name: 'MAGNESIUM CARBONATE' },
	{ icru: 193, name: 'MAGNESIUM FLUORIDE' },
	{ icru: 194, name: 'MAGNESIUM OXIDE' },
	{ icru: 195, name: 'MAGNESIUM TETRABORATE' },
	{ icru: 196, name: 'MERCURIC IODIDE' },
	{ icru: 197, name: 'METHANE' },
	{ icru: 198, name: 'METHANOL' },
	{ icru: 199, name: 'MIX D WAX' },
	{ icru: 200, name: 'MS20 TISSUE SUBSTITUTE' },
	{ icru: 201, name: 'MUSCLE, SKELETAL (ICRP)' },
	{ icru: 202, name: 'MUSCLE, STRIATED (ICRU)' },
	{ icru: 203, name: 'MUSCLE EQUIVALENT LIQUID, WITH SUCROSE' },
	{ icru: 204, name: 'MUSCLE EQUIVALENT LIQUID, NO SUCROSE' },
	{ icru: 205, name: 'NAPHTHALENE' },
	{ icru: 206, name: 'NITROBENZENE' },
	{ icru: 207, name: 'NITROUS OXIDE' },
	{ icru: 208, name: 'NYLON, DU PONT ELVAMIDE 8062' },
	{ icru: 209, name: 'NYLON, TYPE 6 AND 6/6' },
	{ icru: 210, name: 'NYLON, TYPE 6/10' },
	{ icru: 211, name: 'NYLON, TYPE 11 (RILSAN)' },
	{ icru: 212, name: 'OCTANE, LIQUID' },
	{ icru: 213, name: 'PARAFFINWAX' },
	{ icru: 214, name: 'N-PENTANE' },
	{ icru: 215, name: 'PHOTOGRAPHIC EMULSION' },
	{ icru: 216, name: 'PLASTIC SCINTILLATOR (VINYLTOLUENE BASED)' },
	{ icru: 217, name: 'PLUTONIUM DIOXIDE' },
	{ icru: 218, name: 'POLYACRYLONITRILE' },
	{ icru: 219, name: 'POLYCARBONATE (MAKROLON, LEXAN)' },
	{ icru: 220, name: 'POLYCHLOROSTYRENE' },
	{ icru: 221, name: 'POLYETHYLENE' },
	{ icru: 222, name: 'POLYETHYLENE TEREPHTHALATE (MYLAR)' },
	{ icru: 223, name: 'POLYMETHYL METHACRALATE (LUCITE, PERSPEX, PMMA)' },
	{ icru: 224, name: 'POLYOXYMETHYLENE' },
	{ icru: 225, name: 'POLYPROPYLENE' },
	{ icru: 226, name: 'POLYSTYRENE' },
	{ icru: 227, name: 'POLYTETRAFLUOROETHYLENE (TEFLON)' },
	{ icru: 228, name: 'POLYTRIFLUOROCHLOROETHYLENE' },
	{ icru: 229, name: 'POLYVINYL ACETATE' },
	{ icru: 230, name: 'POLYVINYL ALCOHOL' },
	{ icru: 231, name: 'POLYVINYL BUTYRAL' },
	{ icru: 232, name: 'POLYVINYL CHLORIDE' },
	{ icru: 233, name: 'SARAN' },
	{ icru: 234, name: 'POLYVINYLIDENE FLUORIDE' },
	{ icru: 235, name: 'POLYVINYLPYRROLIDONE' },
	{ icru: 236, name: 'POTASSIUM IODIDE' },
	{ icru: 237, name: 'POTASSIUM OXIDE' },
	{ icru: 238, name: 'PROPANE' },
	{ icru: 239, name: 'PROPANE, LIQUID' },
	{ icru: 240, name: 'N-PROPYL ALCOHOL' },
	{ icru: 241, name: 'PYRIDINE' },
	{ icru: 242, name: 'RUBBER, BUTYL' },
	{ icru: 243, name: 'RUBBER, NATURAL' },
	{ icru: 244, name: 'RUBBER, NEOPRENE' },
	{ icru: 245, name: 'SILICON DIOXIDE' },
	{ icru: 246, name: 'SILVER BROMIDE' },
	{ icru: 247, name: 'SILVER CHLORIDE' },
	{ icru: 248, name: 'SILVER HALIDES IN PHOTOGRAPHIC EMULSION' },
	{ icru: 249, name: 'SILVER IODIDE' },
	{ icru: 250, name: 'SKIN (ICRP)' },
	{ icru: 251, name: 'SODIUM CARBONATE' },
	{ icru: 252, name: 'SODIUM IODIDE' },
	{ icru: 253, name: 'SODIUM MONOXIDE' },
	{ icru: 254, name: 'SODIUM NITRATE' },
	{ icru: 255, name: 'STILBENE' },
	{ icru: 256, name: 'SUCROSE' },
	{ icru: 257, name: 'TERPHENYL' },
	{ icru: 258, name: 'TESTES (ICRP)' },
	{ icru: 259, name: 'TETRACHLOROETHYLENE' },
	{ icru: 260, name: 'THALLIUM CHLORIDE' },
	{ icru: 261, name: 'TISSUE, SOFT (ICRP)' },
	{ icru: 262, name: 'TISSUE, SOFT (ICRU, FOUR COMPONENT)' },
	{ icru: 263, name: 'TISSUE-EQUIVALENT GAS (METHANE BASED)' },
	{ icru: 264, name: 'TISSUE-EQUIVALENT GAS (PROPANE BASED)' },
	{ icru: 265, name: 'TITANIUM DIOXIDE' },
	{ icru: 266, name: 'TOLUENE' },
	{ icru: 267, name: 'TRICHLOROETHYLENE' },
	{ icru: 268, name: 'TRIETHYL PHOSPHATE' },
	{ icru: 269, name: 'TUNGSTEN HEXAFLUORIDE' },
	{ icru: 270, name: 'URANIUM DICARBIDE' },
	{ icru: 271, name: 'URANIUM MONOCARBIDE' },
	{ icru: 272, name: 'URANIUM OXIDE' },
	{ icru: 273, name: 'UREA' },
	{ icru: 274, name: 'VALINE' },
	{ icru: 275, name: 'VITON FLUOROELASTOMER' },
	{ icru: 276, name: 'WATER, LIQUID' },
	{ icru: 277, name: 'WATER VAPOR' },
	{ icru: 278, name: 'XYLENE' }
] as const;
